USE [master]
GO

/****** Object:  Database [LWBOILERPLATE]    Script Date: 23.12.2016 11:53:48 ******/
CREATE DATABASE [LWBOILERPLATE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LWBOILERPLATE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.QIDAN\MSSQL\DATA\LWBOILERPLATE.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LWBOILERPLATE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.QIDAN\MSSQL\DATA\LWBOILERPLATE_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LWBOILERPLATE] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LWBOILERPLATE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LWBOILERPLATE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET ARITHABORT OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LWBOILERPLATE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LWBOILERPLATE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LWBOILERPLATE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LWBOILERPLATE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LWBOILERPLATE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET RECOVERY FULL 
GO

ALTER DATABASE [LWBOILERPLATE] SET  MULTI_USER 
GO

ALTER DATABASE [LWBOILERPLATE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LWBOILERPLATE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LWBOILERPLATE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LWBOILERPLATE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LWBOILERPLATE] SET  READ_WRITE 
GO


